spring.application.name=SICE_WEB_2025

# ===============================
# DATOS DE CONEXIÓN (MULTI-TENANT)
# ===============================

# --- CAMPUS 1 (escolares) ---
tenant.campus1.datasource.jdbc-url=jdbc:mysql://localhost:3306/escolares?useSSL=false&allowPublicKeyRetrieval=true
tenant.campus1.datasource.username=root
tenant.campus1.datasource.password=Marinero2003#
tenant.campus1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hikari para Campus 1
tenant.campus1.datasource.maximum-pool-size=20
tenant.campus1.datasource.idle-timeout=600000
tenant.campus1.datasource.connection-timeout=30000
tenant.campus1.datasource.minimum-idle=5

# --- CAMPUS 2 (escolares2) ---
tenant.campus2.datasource.jdbc-url=jdbc:mysql://localhost:3306/escolares_tuxtepec?useSSL=false&allowPublicKeyRetrieval=true
tenant.campus2.datasource.username=root
tenant.campus2.datasource.password=Marinero2003#
tenant.campus2.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hikari para Campus 2
tenant.campus2.datasource.maximum-pool-size=20
tenant.campus2.datasource.idle-timeout=600000
tenant.campus2.datasource.connection-timeout=30000
tenant.campus2.datasource.minimum-idle=5

# ===============================
# JPA / HIBERNATE (Se queda igual, es compartido)
# ==============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none   
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.secret=61x5WAMgkErPS0aJ/DOOpBDLpW6X9TZAa+9TvkwnLF/raX3sXfg+fPg1vApdnkX8sBMjS1blZylZgN73rFPUVQ==

spring.jpa.open-in-view=false