CREATE TABLE IF NOT EXISTS foto_perfil_alumno (
    Id_Alu_FK VARCHAR(40) NOT NULL,
    Url_Foto VARCHAR(512) NOT NULL,
    FechaAct_Foto DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Id_Alu_FK)
);
